redhat-plumbers/systemd-rhel10

.github/advanced-commit-linter.yml
Supported parameters:
* feature - for feature related commits (cross-version)
* bugfix - for bugfix related commits (cross-version)
* doc - for documentation related commits (usually version specific)
* workaround - for workaround related commits (usually version-specific)
* ci - for CI related commits (version specific)
* test - for test related commits (version specific)
* other - for commits that do not fit into any of the above categories or use just `rhel-only`
rhel-only: ci
Related: RHEL-36636
=> (RHEL-36636) ci: Allow to pass parameters together with rhel-only note 

meson.build, meson_options.txt, src/basic/meson.build, src/core/meson.build, src/libsystemd/meson.build, src/partition/meson.build, src/shared/meson.build, src/shutdown/meson.build, src/sysusers/meson.build, src/test/meson.build, src/tmpfiles/meson.build
=> (RHEL-46020) build systemd-executor statically

catalog/systemd.catalog.in, catalog/systemd.pl.catalog.in, man/org.freedesktop.systemd1.xml, src/core/taint.c
In rhel10 we will have separate bin and sbin
RHEL-only: policy
Resolves: RHEL-46277
=> (RHEL-46277) taint: remove unmerged-bin

presets/90-systemd.preset
We noticed that some people are installing systemd* and then have daemons they don't need running. So let's remove resolved from presets so its usage is a bit more deliberate
RHEL-only: policy
Resolves: RHEL-46576
=> (RHEL-46576) presets: remove resolved

.github/advanced-commit-linter.yml, CONTRIBUTING.md, README.md
rhel-only: doc
Related: RHEL-40924
=> (RHEL-40924) doc: add downstream CONTRIBUTING document

.github/workflows/mkosi.yml, src/core/taint.c
rhel-only: ci
Related: RHEL-40924
=> (RHEL-40924) ci: run mkosi test only for Fedora and CentOS Stream

.packit.yml
Since it's only in the RHEL buildroot repo.
rhel-only: ci
Related: RHEL-40924
=> (RHEL-40924) packit: drop the dependency on python3-zstd

src/coredump/coredump.conf
This brings policy inline with RHEL-9.
rhel-only: policy
Related: RHEL-46778
=> (RHEL-46778) coredump: by default process and store core files up to 1GiB

src/core/mount.c, src/core/unit.c, units/basic.target, units/meson.build, units/tmp.mount
=> (RHEL-40924) Make sure /tmp is not on tmpfs

man/systemd.net-naming-scheme.xml, src/shared/netif-naming-scheme.h, src/udev/udev-builtin-net_id.c
=> (RHEL-44416) udev-builtin-net_id: use firmware_node/sun for ID_NET_NAME_SLOT

.packit.yml
`python3dist(zstd)` is now available in AppStream
This reverts commit 43bf3e1a42e2c1a6ecd0ca6fd72c9bc6fe904703.
rhel-only: ci
Related: RHEL-36636
=> (RHEL-36636) Revert "packit: drop the dependency on python3-zstd"

src/systemctl/systemctl-util.c
(cherry picked from commit 09d6038d833468ba7c24c658597387ef699ca4fd)
Resolves: RHEL-55132
=> (RHEL-55132) systemctl: do not try to acquire triggering units for template units

src/basic/cgroup-util.c
=> (RHEL-55746) cgroup-util: Don't try to open pidfd for kernel threads

src/basic/cgroup-util.c
The kernel patch was reverted so let's try again to open pidfds for kernel threads.
This reverts commit ead48ec35c863650944352a3455f26ce3b393058.
(cherry picked from commit 1ce69e06615e69692a6d02d447acfd77f5d44631)
follow-up to:
- #34
=> (RHEL-52634) Revert "cgroup-util: Don't try to open pidfd for kernel threads"

src/ukify/test/test_ukify.py
(cherry picked from commit 5121f7c45b37afca53c89f42123b1dd6a04fa80f)
Related: RHEL-52634
=> (RHEL-52634) ukify: Skip test on architectures without UEFI

.github/tracker-validator.yml
rhel-only: ci
Related: RHEL-57603
=> (RHEL-57603) ci: rename beta branch to match dist-git name

rules.d/50-udev-default.rules.in
PTP device symlink creation rules are currently executed only when the udev action is 'add'. If a user reloads the rules and runs the udevadm trigger command to reapply changes, the symlink may be deleted, which can prevent the chronyd service from restarting properly.
Signed-off-by: Chengen Du <chengen.du@canonical.com>
(cherry picked from commit 6bd12be3fa7761f190e17efdbdbff4440da7528b)
Resolves: RHEL-59871
=> (RHEL-59871) udev: Handle PTP device symlink properly on udev action 'change'

src/core/socket.c, test/units/TEST-04-JOURNAL.stopped-socket-activation.sh
(cherry picked from commit 941a12dcba57f6673230a9c413738c51374d2998)
Resolves: RHEL-60896
=> (RHEL-60896) socket: fix socket activation of stopped services with pinned FD store

.github/workflows/deploy-man-pages.yml
rhel-only: ci
Related: RHEL-57603
=> (RHEL-57603) ci: use ubuntu 22:04 for deploy of man pages

src/core/dbus-cgroup.c, src/core/dbus-manager.c, src/core/dbus.c, src/core/dbus.h, src/core/manager-serialize.c, src/core/manager.c, src/core/manager.h, src/core/unit-serialize.c, src/home/homed-manager-bus.c, src/hostname/hostnamectl.c, src/login/logind-brightness.c, src/machine/machinectl.c, src/machine/machined-dbus.c, src/run/run.c, src/shared/bus-get-properties.c, src/shared/bus-get-properties.h, src/shared/bus-map-properties.c, src/shared/bus-message-util.c, src/shared/bus-message-util.h, src/shared/bus-util.c, src/shared/bus-util.h, src/shared/serialize.c, src/shared/serialize.h, src/systemctl/systemctl-list-units.c, src/timedate/timedated.c
=> (RHEL-73780) Stash the subscriber list when we disconenct from the bus

src/ukify/test/test_ukify.py
The test needs binutils 2.42 to work on the architecture, but we only have 2.41 in RHEL 10.
Signed-off-by: Andrea Bolognani <abologna@redhat.com>
rhel-only: test
Resolves: RHEL-85854
/cc @andreabolognani
=> (RHEL-85854) test_ukify: Skip on riscv64

man/systemctl.xml
Resolves: RHEL-97762
rhel-only: doc
=> (RHEL-97762) man: mention RHEL documentation in systemctl's man page

src/ukify/ukify.py
Fixes https://github.com/systemd/systemd/issues/34780. The number in the header
is the size of the *compressed* data, so for gzip we'd read the initial part of
the decompressed data (equal to the size of the compressed data) and not find
the version string. Later on, Fedora switched to zstd compression, and there we
correctly use the number as the size of the compressed data, so we stopped
hitting the issue, but we should still fix it for older kernels.
I verified that the fix works for gzip-compressed kernels. I also made the same
change for the code for lzma compression. I'm pretty sure it is the right thing,
even though I don't have such a kernel at hand to test.
>>> ukify.Uname.scrape('/lib/modules/6.12.0-0.rc2.24.fc42.aarch64/vmlinuz')
Real-Mode Kernel Header magic not found
+ …
=> (RHEL-97625) ukify: fix version detection for aarch64 zboot kernels with gzip or lzma compression

src/basic/socket-util.c, src/basic/socket-util.h, src/core/socket.c
On Linux, read() on a message queue descriptor returns the message queue statistics, not the actual message queue data.  We need to use mq_receive() to drain the queues instead.
Fixes a problem where a POSIX message queue socket unit with messages in the queue at shutdown time could result in a hang on reboot/shutdown.
(cherry picked from commit ffb6adb76367d5ab7d43937ccaac5947717b5b78)
Resolves: RHEL-100553
=> (RHEL-100553) flush_ports: flush POSIX message queues properly

src/core/transaction.c
Follow-up for 3cf6a3a3d4acf8347ccd0250274f517e6b2e9fe6
(cherry picked from commit 1c8d653d2b8a82ed3944f03c2dea25ad1e2cc967)
Related: RHEL-106260
=> (RHEL-106260) core/transaction: do not attempt to log "n/a" as a journal field

src/ukify/ukify.py
SBAT section of UKI may contain \u000 null characters. Rstrip them, and if there's anything left in the middle, escape them so they are displayed as text.
Fixes #38606
(cherry picked from commit 776991a3f349d9c99fd166a0c87fcd2bc1bf92a5)
Resolves: RHEL-109552
=> (RHEL-109552) ukify: rstrip and escape binary null characters from 'inspect' output

src/ukify/ukify.py
The padding was done to expand the new section contents to the expected size of the new section. And this then would be used for the content in the existing section. The new section cannot be larger than the old section, but it can be smaller. If the new section was smaller, then we'd not write enough padding and the output file would be corrupted.
This was observed in CI when the .sbat section in the stub was padded to 1k. The UKI with an .sbat section that was merged and was fairly short would hit this scenario and be corrupted.
(cherry picked from commit ec1d031f3de02f84beca89e2b402d085fba62be4)
Resolves: RHEL-114414
/cc @DaanDeMeyer
=> (RHEL-114414) ukify: fix insertion of padding in merged sections
